services:
  - type: web
    name: phantom-os-terminal
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: phantom-os-terminal
          property: port
    autoDeploy: true
    branch: main
    healthCheckPath: /